package mooc.dal;

import mooc.model.*;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class Volunteer_to_SchoolDao {
	protected ConnectionManager connectionManager;

	private static Volunteer_to_SchoolDao instance = null;
	protected Volunteer_to_SchoolDao() {
		connectionManager = new ConnectionManager();
	}
	public static Volunteer_to_SchoolDao getInstance() {
		if(instance == null) {
			instance = new Volunteer_to_SchoolDao();
		}
		return instance;
	}

	protected int id;
	protected int volunteerId;
	protected int schoolId;

	// public create(Volunteer_to_School volunteer_to_school)
	// adds a new Volunteer_to_School to the database
	public Volunteer_to_School create(Volunteer_to_School volunteer_to_school) throws SQLException {
		String insertVolunteer_to_School = "INSERT INTO Volunteer_To_School(VolunteerId,SchoolId) VALUES(?,?);";
		Connection connection = null;
		PreparedStatement insertStmt = null;
		// below needed for autogenerated keys
		ResultSet resultKey = null;
		// end autogenerated key code 1of4
		try {
			connection = connectionManager.getConnection();
			insertStmt = connection.prepareStatement(insertVolunteer_to_School,
					// below needed for autogenerated keys
					Statement.RETURN_GENERATED_KEYS);
			// end autogenerated key code 2of4
			insertStmt.setInt(1, volunteer_to_school.getVolunteerID());
			insertStmt.setInt(2, volunteer_to_school.getSchoolID());

			insertStmt.executeUpdate();

			// bellow autogenerates key 
			resultKey = insertStmt.getGeneratedKeys();
			int id = -1;
			if(resultKey.next()) {
				id = resultKey.getInt(1);
			} else {
				throw new SQLException("Unable to retrieve auto-generated key.");
			}
			volunteer_to_school.setID(id);
			// end autogenerated key code 3of4
			return volunteer_to_school;

		} catch (SQLException e) {
			e.printStackTrace();
			throw e;
		} finally {
			if(connection != null) {
				connection.close();
			}
			if(insertStmt != null) {
				insertStmt.close();
			}
			// bellow used for autogenerated key
			if(resultKey != null) {
				resultKey.close();
			}
			// end autogenerated key code 4of4
		}
	}

	public Volunteer_to_School updateSchool(Volunteer_to_School volun, int SchoolID)throws SQLException{
		String updateStudents = "UPDATE Volunteer_to_School SET SchoolID=? WHERE ID=?";
		Connection connection = null;
		PreparedStatement updateStmt = null;
		try {
			connection = connectionManager.getConnection();
			updateStmt = connection.prepareStatement(updateStudents);
			updateStmt.setInt(1, SchoolID);
			updateStmt.setInt(2, volun.getID());
			updateStmt.executeUpdate();
			volun.setSchoolID(SchoolID);
			return volun;
		} catch (SQLException e) {
			e.printStackTrace();
			throw e;
		} finally {
			if(connection != null) {
				connection.close();
			}
			if(updateStmt != null) {
				updateStmt.close();
			}
		}
	}

	// public Volunteer_to_School delete(Volunteer_to_School volunteer_to_school) 
	// Given a Volunteer_to_School, removes it from the database
	public Volunteer_to_School delete(Volunteer_to_School volunteer_to_school) throws SQLException {
		String deleteVolunteer_to_School = "DELETE FROM Volunteer_To_School WHERE ID=?;";
		Connection connection = null;
		PreparedStatement deleteStmt = null;
		try {
			connection = connectionManager.getConnection();
			deleteStmt = connection.prepareStatement(deleteVolunteer_to_School);
			deleteStmt.setInt(1, volunteer_to_school.getID());
			deleteStmt.executeUpdate();

			// Return null so the caller can no longer operate on the Volunteer instance
			return null;
		} catch (SQLException e) {
			e.printStackTrace();
			throw e;
		} finally {
			if(connection != null) {
				connection.close();
			}
			if(deleteStmt != null) {
				deleteStmt.close();
			}
		}
	}

	// public Volunteer_to_School getVolunteer_to_SchoolFromID(int id)
	// given a vounteer_to_school ID, retrieves the matching Volunteer_to_School
	public Volunteer_to_School getVolunteer_to_SchoolFromID(int id) throws SQLException {
		String selectVolunteer_to_School = "SELECT * FROM Volunteer_To_School WHERE ID=?;";
		Connection connection = null;
		PreparedStatement selectStmt = null;
		ResultSet results = null;
		try {
			connection = connectionManager.getConnection();
			selectStmt = connection.prepareStatement(selectVolunteer_to_School);
			selectStmt.setInt(1, id);
			// Note that we call executeQuery(). This is used for a SELECT statement
			// because it returns a result set. For more information, see:
			// http://docs.oracle.com/javase/7/docs/api/java/sql/PreparedStatement.html
			// http://docs.oracle.com/javase/7/docs/api/java/sql/ResultSet.html
			results = selectStmt.executeQuery();
			// You can iterate the result set (although the example below only retrieves 
			// the first record). The cursor is initially positioned before the row.
			// Furthermore, you can retrieve fields by name and by type.
			if(results.next()) {
				Integer resultID = results.getInt("ID");
				Integer volunteerId = results.getInt("VolunteerId");
				Integer schoolId = results.getInt("SchoolId");

				Volunteer_to_School volunteer_to_school = new Volunteer_to_School(resultID, volunteerId, schoolId);
				return volunteer_to_school;
			}
		} catch (SQLException e) {
			e.printStackTrace();
			throw e;
		} finally {
			if(connection != null) {
				connection.close();
			}
			if(selectStmt != null) {
				selectStmt.close();
			}
			if(results != null) {
				results.close();
			}
		}
		return null;
	}

}