package mooc.model;

//import java.util.Date;
import java.sql.Date;

public class Active_Classes {
	protected int ActiveID;
	protected int StudentID;
	protected int MOOCID;
	protected Date StartDate;
	protected Date EndDate;
	
	public Active_Classes(int ActiveID,int StudentID,int MOOCID,Date StartDate,Date EndDate){
		this.ActiveID=ActiveID;
		this.StudentID=StudentID;
		this.MOOCID=MOOCID;
		this.StartDate=StartDate;
		this.EndDate=EndDate;
	}
	
	// without autogenerated key
	public Active_Classes(int StudentID,int MOOCID,Date StartDate,Date EndDate){
		this.StudentID=StudentID;
		this.MOOCID=MOOCID;
		this.StartDate=StartDate;
		this.EndDate=EndDate;
	}
	
	// used for foreign key reference and lookup
	public Active_Classes(int ActiveID){
		this.ActiveID=ActiveID;
	}

	public int getActiveID() {
		return ActiveID;
	}

	public void setActiveID(int activeID) {
		ActiveID = activeID;
	}

	public int getStudentID() {
		return StudentID;
	}

	public void setStudentID(int studentID) {
		StudentID = studentID;
	}

	public int getMOOCID() {
		return MOOCID;
	}

	public void setMOOCID(int mOOCID) {
		MOOCID = mOOCID;
	}

	public Date getStartDate() {
		return StartDate;
	}

	public void setStartDate(Date startDate) {
		StartDate = startDate;
	}

	public Date getEndDate() {
		return EndDate;
	}

	public void setEndDate(Date endDate) {
		EndDate = endDate;
	}
	
}
