package mooc.model;

public class Companies {
	protected int ID;
	protected String Name;
	protected String Location;
	protected String Website;
	
	// full constructor
	public Companies(int ID,String Name,String Location,String Website){
		this.ID=ID;
		this.Name=Name;
		this.Location=Location;
		this.Website=Website;
	}

	// constructor without autogenerated ID
	public Companies(String Name,String Location,String Website){
		this.Name=Name;
		this.Location=Location;
		this.Website=Website;
	}

	public int getID() {
		return ID;
	}

	public void setID(int iD) {
		ID = iD;
	}

	public String getName() {
		return Name;
	}

	public void setName(String name) {
		Name = name;
	}

	public String getLocation() {
		return Location;
	}

	public void setLocation(String location) {
		Location = location;
	}

	public String getWebsite() {
		return Website;
	}

	public void setWebsite(String website) {
		Website = website;
	}

}
