package mooc.model;

public class Main_MOOC {
	protected int ID;
	protected String Name;
	protected String Description;
	protected String Source;
	protected String Direct_Link;
	protected boolean Offered;
	protected int Difficulty;
	protected String Type;
	protected int Length;
	
	public Main_MOOC(int ID,String Name,String Description,String Source,String Direct_Link,
			boolean Offered,int Difficulty,String Type,int Length){
		this.ID=ID;
		this.Name=Name;
		this.Description=Description;
		this.Source=Source;
		this.Direct_Link=Direct_Link;
		this.Offered=Offered;
		this.Difficulty=Difficulty;
		this.Type=Type;
		this.Length=Length;	
	}

	// constructor without autogenerated key
	public Main_MOOC(String Name,String Description,String Source,String Direct_Link,
			boolean Offered,int Difficulty,String Type,int Length){
		this.Name=Name;
		this.Description=Description;
		this.Source=Source;
		this.Direct_Link=Direct_Link;
		this.Offered=Offered;
		this.Difficulty=Difficulty;
		this.Type=Type;
		this.Length=Length;	
	}
	
	public int getID() {
		return ID;
	}

	public void setID(int iD) {
		ID = iD;
	}

	public String getName() {
		return Name;
	}

	public void setName(String name) {
		Name = name;
	}

	public String getDescription() {
		return Description;
	}

	public void setDescription(String description) {
		Description = description;
	}

	public String getSource() {
		return Source;
	}

	public void setSource(String source) {
		Source = source;
	}

	public String getDirect_Link() {
		return Direct_Link;
	}

	public void setDirect_Link(String direct_Link) {
		Direct_Link = direct_Link;
	}

	public boolean isOffered() {
		return Offered;
	}

	public void setOffered(boolean offered) {
		Offered = offered;
	}

	public int getDifficulty() {
		return Difficulty;
	}

	public void setDifficulty(int difficulty) {
		Difficulty = difficulty;
	}

	public String getType() {
		return Type;
	}

	public void setType(String type) {
		Type = type;
	}

	public int getLength() {
		return Length;
	}

	public void setLength(int length) {
		Length = length;
	}

}
