package mooc.model;

public class Volunteer_to_School {
	protected int ID;
	protected int VolunteerID;
	protected int SchoolID;
	
	public Volunteer_to_School(int ID,int VolunteerID,int SchoolID){
		this.ID=ID;
		this.VolunteerID=VolunteerID;
		this.SchoolID=SchoolID;
	}
	
	// constructor without autogenerated key
	public Volunteer_to_School(int VolunteerID,int SchoolID){
		this.VolunteerID=VolunteerID;
		this.SchoolID=SchoolID;
	}

	public int getID() {
		return ID;
	}

	public void setID(int iD) {
		ID = iD;
	}

	public int getVolunteerID() {
		return VolunteerID;
	}

	public void setVolunteerID(int volunteerID) {
		VolunteerID = volunteerID;
	}

	public int getSchoolID() {
		return SchoolID;
	}

	public void setSchoolID(int schoolID) {
		SchoolID = schoolID;
	}
}
