package mooc.model;

public class Volunteer {
	protected int ID;
	protected String First_Name;
	protected String Last_Name;
	protected String Email;
	protected int Association;
	
	public Volunteer(int ID,String First_Name,String Last_Name,String Email,
			int Association){
		this.ID=ID;
		this.First_Name=First_Name;
		this.Last_Name=Last_Name;
		this.Email=Email;
		this.Association=Association;
	}
	
	// constructor without Autogenerated Key
	public Volunteer(String First_Name,String Last_Name,String Email,
			int Association){
		this.First_Name=First_Name;
		this.Last_Name=Last_Name;
		this.Email=Email;
		this.Association=Association;
	}
	
	// constructor without Autogenerated Key - work in progress
		public Volunteer(String First_Name,String Last_Name,String Email){
			this.First_Name=First_Name;
			this.Last_Name=Last_Name;
			this.Email=Email;
		}

	public int getID() {
		return ID;
	}

	public void setID(int iD) {
		ID = iD;
	}

	public String getFirst_Name() {
		return First_Name;
	}

	public void setFirst_Name(String first_Name) {
		First_Name = first_Name;
	}

	public String getLast_Name() {
		return Last_Name;
	}

	public void setLast_Name(String last_Name) {
		Last_Name = last_Name;
	}

	public String getEmail() {
		return Email;
	}

	public void setEmail(String email) {
		Email = email;
	}

	public int getAssociation() {
		return Association;
	}

	public void setAssociation(int association) {
		Association = association;
	}
	
}
